package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"melom/web-services/internals/db"
)

// Opt in with TEST_DATABASE_URL. All writes use a temporary, isolated schema.
func TestPatientPersistence(t *testing.T) {
	databaseURL := os.Getenv("TEST_DATABASE_URL")
	if databaseURL == "" {
		t.Skip("set TEST_DATABASE_URL to run PostgreSQL integration tests")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 45*time.Second)
	defer cancel()
	admin, err := pgx.Connect(ctx, databaseURL)
	if err != nil {
		t.Fatal("cannot connect to test database")
	}
	t.Cleanup(func() { _ = admin.Close(context.Background()) })
	schema := fmt.Sprintf("patient_test_%d", time.Now().UnixNano())
	quotedSchema := pgx.Identifier{schema}.Sanitize()
	if _, err := admin.Exec(ctx, "CREATE SCHEMA "+quotedSchema); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cleanupCancel()
		if _, err := admin.Exec(cleanupCtx, "DROP SCHEMA "+quotedSchema+" CASCADE"); err != nil {
			t.Errorf("test schema cleanup failed: %v", err)
		}
	})
	config, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		t.Fatal("invalid test database configuration")
	}
	config.ConnConfig.RuntimeParams["search_path"] = schema
	pool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		t.Fatal("cannot create test pool")
	}
	t.Cleanup(pool.Close)
	// These fixture columns match the existing application's schema before migration.
	_, err = pool.Exec(ctx, `
 CREATE TABLE nutricionistas (id integer PRIMARY KEY, usuario_id integer NOT NULL UNIQUE);
 CREATE TABLE pacientes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nutricionista_id integer NOT NULL REFERENCES nutricionistas(id),
  nome varchar NOT NULL, data_nascimento date, sexo varchar,
  altura_cm numeric, peso_kg numeric, telefone varchar
 );
 INSERT INTO nutricionistas (id, usuario_id) VALUES (3, 7), (4, 8);
 INSERT INTO pacientes (nutricionista_id, nome, data_nascimento, sexo, altura_cm, peso_kg, telefone)
 VALUES (4, 'Existing patient', '1990-01-01', 'Masculino', 175, 70, '11999999999');`)
	if err != nil {
		t.Fatal(err)
	}
	migration, err := os.ReadFile("../../migrations/001_patient_email.sql")
	if err != nil {
		t.Fatal(err)
	}
	// Reapplying the additive migration must also be safe.
	for range 2 {
		if _, err := pool.Exec(ctx, string(migration)); err != nil {
			t.Fatal(err)
		}
	}

	response := patientRequest(pool, "?usuario_id=7", validPatientJSON, patientTestNow)
	if response.Code != http.StatusCreated {
		t.Fatalf("expected 201: %d %s", response.Code, response.Body)
	}
	var created struct {
		Patient Patient `json:"paciente"`
	}
	if err := json.Unmarshal(response.Body.Bytes(), &created); err != nil {
		t.Fatal(err)
	}
	// A separate connection proves the INSERT has been committed.
	reader, err := pgx.ConnectConfig(ctx, config.ConnConfig.Copy())
	if err != nil {
		t.Fatal("cannot create independent test connection")
	}
	t.Cleanup(func() { _ = reader.Close(context.Background()) })
	var stored Patient
	err = reader.QueryRow(ctx, `SELECT id, nutricionista_id, nome, to_char(data_nascimento,'YYYY-MM-DD'), sexo, altura_cm, peso_kg, COALESCE(telefone,''), email FROM pacientes WHERE id=$1`, created.Patient.ID).Scan(
		&stored.ID, &stored.NutricionistaID, &stored.Nome, &stored.DataNascimento,
		&stored.Sexo, &stored.Altura, &stored.Peso, &stored.Telefone, &stored.Email,
	)
	if err != nil {
		t.Fatal(err)
	}
	expected := Patient{ID: created.Patient.ID, NutricionistaID: 3, Nome: "Ana Silva", DataNascimento: "1995-04-20", Sexo: "Feminino", Altura: 168, Peso: 64.5, Email: "ana@example.com"}
	if stored != expected || created.Patient != expected {
		t.Fatalf("incorrect stored or returned patient: stored=%+v response=%+v", stored, created.Patient)
	}

	for _, query := range []string{"?usuario_id=7", "?usuario_id=999"} {
		body := validPatientJSON
		status := http.StatusNotFound
		if query == "?usuario_id=7" {
			body = strings.Replace(body, "64.5", "-1", 1)
			status = http.StatusBadRequest
		}
		failed := patientRequest(pool, query, body, patientTestNow)
		if failed.Code != status {
			t.Fatalf("expected %d, got %d", status, failed.Code)
		}
	}
	var count int
	if err := reader.QueryRow(ctx, `SELECT count(*) FROM pacientes`).Scan(&count); err != nil || count != 2 {
		t.Fatalf("failed requests inserted a row: count=%d err=%v", count, err)
	}

	// Exercise the existing list route, including email/phone NULL compatibility and ownership.
	previousPool := db.Pool
	db.Pool = pool
	t.Cleanup(func() { db.Pool = previousPool })
	router := gin.New()
	router.GET("/patients", ListPatients)
	for _, userID := range []string{"7", "8"} {
		listed := httptest.NewRecorder()
		router.ServeHTTP(listed, httptest.NewRequest(http.MethodGet, "/patients?usuario_id="+userID, nil))
		if listed.Code != http.StatusOK {
			t.Fatalf("list failed: %s", listed.Body)
		}
		var result struct {
			Patients []Patient `json:"pacientes"`
		}
		if err := json.Unmarshal(listed.Body.Bytes(), &result); err != nil {
			t.Fatal(err)
		}
		if len(result.Patients) != 1 {
			t.Fatalf("ownership filter failed: %+v", result.Patients)
		}
		if userID == "7" && result.Patients[0] != expected {
			t.Fatalf("new patient cannot be listed correctly: %+v", result.Patients[0])
		}
		if userID == "8" && (result.Patients[0].Email != "" || result.Patients[0].Telefone != "11999999999") {
			t.Fatal("existing patient contact was not preserved")
		}
	}
}
