import type { Metadata } from "next";
import "../tokens/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className="mx-auto max-w-screen-xl">{children}</body>
    </html>
  );
}
